In [3]:
#Question1

import numpy as np
a = np.random.rand(10,1)              
print(a)
b = np.mean(a)
print(b)

[[0.86099348]
 [0.99629047]
 [0.18035713]
 [0.55727434]
 [0.02133476]
 [0.05149687]
 [0.81142798]
 [0.14275457]
 [0.77953274]
 [0.11616971]]
0.4517632044860159


In [13]:
#Question 2

c = np.random.rand(20,1)
print(c)
x = np.var(c)
print (x)
y =np.std(c)
print (y)


[[0.66248054]
 [0.02868225]
 [0.34388254]
 [0.83700979]
 [0.92389751]
 [0.59620959]
 [0.78993669]
 [0.80209002]
 [0.68700999]
 [0.98209279]
 [0.51962892]
 [0.23749706]
 [0.77449725]
 [0.66939225]
 [0.80727251]
 [0.58755911]
 [0.94437783]
 [0.27424855]
 [0.6790178 ]
 [0.84628913]]
0.06230176414830311
0.24960321341742198


In [5]:
#Question 3

A = np.random.random([10,20])
B = np.random.random([20,25])
C = (np.matmul(A,B))
print (A)
print (B)
print (np.reshape(C,(10,25)))
print (np.sum(C))

[[0.36464701 0.22273149 0.77952647 0.66500861 0.85921814 0.96847922
  0.18099421 0.66271323 0.68815495 0.30824518 0.2244472  0.67743362
  0.04089485 0.09436358 0.80985656 0.0951042  0.4877025  0.55202357
  0.52933949 0.72107213]
 [0.44253866 0.01155918 0.16572014 0.19888772 0.89030149 0.1826619
  0.20621434 0.85182128 0.7556789  0.12906096 0.65777078 0.52273688
  0.0097663  0.3257874  0.88990652 0.93149082 0.81763096 0.84132369
  0.03455132 0.66368172]
 [0.33976234 0.53545108 0.16068751 0.71870299 0.93281294 0.64684709
  0.6398048  0.2139405  0.62791895 0.32129871 0.67083588 0.82288552
  0.38932847 0.81729269 0.38715858 0.83248163 0.93739359 0.85806183
  0.57885416 0.00565997]
 [0.99998729 0.5604867  0.6595613  0.91017672 0.93501027 0.85599478
  0.71828137 0.50617443 0.27106276 0.09226006 0.47238389 0.54798448
  0.77052077 0.64555899 0.00214887 0.29059934 0.71498751 0.11593307
  0.28577168 0.28280656]
 [0.56038858 0.2026475  0.16989823 0.63928852 0.03447391 0.58540819
  0.58390354 0.38

In [7]:
#Question 4
A = np.random.random([10,1])
print(A)

import math

def func(x):
    y=1 / (1 + math.exp(-x))
    return y
res=list(map(func,A))
print(np.array(res))

[[0.84331946]
 [0.12778958]
 [0.23144937]
 [0.41472486]
 [0.76288468]
 [0.70332257]
 [0.34709259]
 [0.78732574]
 [0.43777279]
 [0.70969176]]
[0.69916387 0.53190399 0.55760542 0.60222027 0.6819797  0.66892402
 0.58591236 0.68725683 0.6077282  0.67033305]
